User/login 유저 스키마 수정, 미들웨어 추가 위해 PR
tastekim/WeAllLie-BE pull request #48
Opened 2022-11-14 15:42 UTC by Minhyeong-S

2022-11-14 15:44 UTC, kimhsno1 commented
확인 했습니다!

2022-11-14 15:47 UTC, kimhsno1 requested changes
.

2022-11-14 16:00 UTC, tastekim reviewed
파일 코드 내에 코멘트 확인 부탁드려요 !

그리고 추가로 각 파일에서 
```javascript
module.exports = new UserProvider();
```
에서 class를 인스턴스로 모듈화 하는 이유가 있을까요?

2022-11-14 16:00 UTC, tastekim commented on src/users/jwt.js
> +  jwt = require('jsonwebtoken');
외부에서 'jsonwebtoken'을 require하고 class 안에서 또 require하는 이유가 있을까요?

2022-11-14 16:00 UTC, tastekim commented on src/users/util-funtion.js
> +  };
autoIncrease 함수 안의 a라는 변수는 this.lastNum의 reuturn값인데 그럼 a의 값은 기본형 데이터로써 메모리에 저장되어있는게 아니라 a라는 변수가 참조될 때마다 lastNum에서 DB를 계속 거쳐야하는거면 클로저 함수를 사용할 의미가 없어보인다고 생각합니다,,!

차라리 lastNum의 return값에 +1을 해서 autoIncrease 대신에 lastNum의 return값으로 _id값을 부여하는건 어떻게 생각하시나요?

2022-11-14 16:07 UTC, tastekim commented
> .

이?

2022-11-14 16:56 UTC, closed without merging

2022-11-15 00:23 UTC, Minhyeong-S commented on src/users/jwt.js
> +  jwt = require('jsonwebtoken');
다시 테스트 해본 결과
외부에 한 번만 require 하면 정상 작동했고,
내부에만 있을 경우 오류가 발생했습니다.
외부에만 남기는 것으로 수정했습니다!

2022-11-15 00:27 UTC, Minhyeong-S commented on src/users/util-funtion.js
> +  };
네 어짜피 db를 거치게 되어서 의미가 없는 것 같아서 클로저 함수는 사용하지 않기로 했습니다!
user-provider.js 파일 내에 db에서 값을 불러오는 로직이 있는 상태라 util-function.js 파일 자체가 지금은 필요가 없어서 삭제했습니다!

2022-11-15 00:34 UTC, Minhyeong-S commented
1. 클래스 자체를 모듈화해서 내보낼 경우 임포트한 파일에서 
const UserProvider = require(./user-provider)
const userProvider = new UserProvider() 
이런식으로 한 번 더 인스턴스 선언을 하고 사용하게 되는데 
인스턴스 자체를 내보내면 인스턴스 선언 과정이 생략되어서 좀 더 코드가 간결해지기에 이렇게 사용했습니다!
2. ZDevTools는 제가 .gitignore에 추가해두고 사용하는 개인 폴더인데 자꾸 깃에 올라가네요 ㅠㅠ 
이유를 모르겠습니다 ㅠㅠ